#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 'build-{build}'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
- cmd: >-
    git --version

    cmake --version

    set PATH=C:\Python36-x64;%PATH%

    python --version

# clone directory
clone_folder: c:\projects\render_pipeline_cpp_ci

# environment variables
environment:
  CMAKE_PREFIX_PATH: C:\projects\_install
  BOOST_ROOT: C:\Libraries\boost_1_64_0
  FREETYPE_DIR: C:\projects\_install\panda3d-thirdparty\win-libs-vc14-x64\freetype

# build cache to preserve files/folders between builds
cache:
    - C:\projects\_install

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# to run your custom scripts instead of automatic MSBuild
build_script:
- cmd: >-
    python build.py all --cmake-generator "Visual Studio 15 2017 Win64" --install-prefix="C:/projects/_install"
